baseURL = 'https://www.bytekeeper.org/'
languageCode = 'en-us'
title = 'bytekeeper.org'
theme = ['PaperMod', 'plausible-hugo']

[params]
ShowRssButtonInSectionTermList = true

[[params.socialIcons]]
name = "github"
title = "My GitHub"
url = "https://github.com/Bytekeeper/"

[params.plausible]
enable = true
domain = "bytekeeper.org"
selfhosted_domain = "plausible.bytekeeper.org"
