baseURL = 'https://www.bytekeeper.org/'
languageCode = 'en-us'
title = 'bytekeeper.org'
theme = 'PaperMod'

[params]
ShowRssButtonInSectionTermList = true

[[params.socialIcons]]
name = "github"
title = "My GitHub"
url = "https://github.com/Bytekeeper/"
